name: Direct Test Result

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  test:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.issue.pull_request && github.event.comment.body == '/direct-test') }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: feature/testing-implementation
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests with output capture
      run: |
        mkdir -p test-results
        npm test > test-results/output.txt 2>&1 || true
        
    - name: Create detailed results
      run: |
        echo "# Test Results" > test-results/report.md
        echo "\`\`\`" >> test-results/report.md
        cat test-results/output.txt >> test-results/report.md
        echo "\`\`\`" >> test-results/report.md
      
    - name: Commit and push test results
      uses: EndBug/add-and-commit@v9
      with:
        add: 'test-results'
        message: 'Add concrete test results'
        push: true