name: Direct Test Result

on:
  push:
    branches:
      - fix/github-actions-artifact
  workflow_dispatch:

jobs:
  just-run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Create test result directory
      run: |
        mkdir -p test-results
        echo "# Test Result" > test-results/test-output.md
        echo "This is a simple test to verify GitHub Actions is working." >> test-results/test-output.md
        
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: simple-test-results
        path: test-results/
        if-no-files-found: warn