name: Test-Driven Development

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        id: run-tests
        run: npm test
        continue-on-error: true
      
      - name: Generate test results
        if: always()
        run: |
          echo "TEST_PASSED=${{ steps.run-tests.outcome == 'success' }}" >> $GITHUB_ENV
          echo "TEST_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
          
      - name: Create results summary
        if: always()
        run: |
          echo "# Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [[ "${{ env.TEST_PASSED }}" == "true" ]]; then
            echo "✅ **PASSED**" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **FAILED**" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Run at: ${{ env.TEST_TIMESTAMP }}" >> $GITHUB_STEP_SUMMARY
          echo "Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "Branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
      
      - name: Generate test results JSON
        if: always()
        run: |
          echo '{
            "passed": ${{ steps.run-tests.outcome == 'success' }},
            "timestamp": "${{ env.TEST_TIMESTAMP }}",
            "run_id": "${{ github.run_id }}",
            "run_number": "${{ github.run_number }}",
            "commit_sha": "${{ github.sha }}",
            "branch": "${{ github.ref_name }}"
          }' > test-results.json
      
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test-results.json
          retention-days: 1